#displayName: AdminAPI & WebUI
#type: middleware

# import: github.com/Miromani4/traefik-plugin-AdminAPI_WebUI

# summary: 'Adds admin API and web interface for creating and editing dynamic files, configuring Traefik!'

# iconPath: ./docs/img/logo.png

# testData:
#   root: /tmp/

displayName: AdminAPI_WebUI
type: middleware

import: github.com/Miromani4/traefik-plugin-AdminAPI_WebUI

summary: 'add Admin API & Web UI for Traefik configured dynamic files!'

iconPath: ./docs/img/logo.png

testData:
  root: /tmp/