version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=ERROR
      - --experimental.localPlugins.traefik_plugin_AdminAPI_WebUI.modulename=github.com/Miromani4/traefik-plugin-AdminAPI_WebUI
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/plugins-local/src/github.com/Miromani4/traefik-plugin-AdminAPI_WebUI
    labels:
      traefik.http.routers.waeb.rule: Host(`waeb.localhost`)
      traefik.http.routers.waeb.middlewares: AdminAPI_WebUI
      traefik.http.middlewares.waeb2.plugin.traefik-plugin-AdminAPI_WebUI.root: .
